// <auto-generated />
using System;
using FootBallLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FootBallLib.Migrations
{
    [DbContext(typeof(FootBallContext))]
    [Migration("20200519104550_WithTranfers")]
    partial class WithTranfers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FootBallLib.Models.Speler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rugnummer")
                        .HasColumnType("int");

                    b.Property<int?>("TeamStamnummer")
                        .HasColumnType("int");

                    b.Property<long>("Waarde")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamStamnummer");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("FootBallLib.Models.Team", b =>
                {
                    b.Property<int>("Stamnummer")
                        .HasColumnType("int");

                    b.Property<string>("Bijnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stamnummer");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootBallLib.Models.Tranfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NewTeamStamnummer")
                        .HasColumnType("int");

                    b.Property<int?>("OldTeamStamnummer")
                        .HasColumnType("int");

                    b.Property<int?>("SpelerId")
                        .HasColumnType("int");

                    b.Property<long>("TranferPrijs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NewTeamStamnummer");

                    b.HasIndex("OldTeamStamnummer");

                    b.HasIndex("SpelerId");

                    b.ToTable("Tranfers");
                });

            modelBuilder.Entity("FootBallLib.Models.Speler", b =>
                {
                    b.HasOne("FootBallLib.Models.Team", "Team")
                        .WithMany("Spelers")
                        .HasForeignKey("TeamStamnummer");
                });

            modelBuilder.Entity("FootBallLib.Models.Tranfer", b =>
                {
                    b.HasOne("FootBallLib.Models.Team", "NewTeam")
                        .WithMany()
                        .HasForeignKey("NewTeamStamnummer");

                    b.HasOne("FootBallLib.Models.Team", "OldTeam")
                        .WithMany()
                        .HasForeignKey("OldTeamStamnummer");

                    b.HasOne("FootBallLib.Models.Speler", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerId");
                });
#pragma warning restore 612, 618
        }
    }
}
